apiVersion: v1
kind: Service
metadata:
  labels:
    app: hotrod
  name: hotrod
spec:
  ports:
  - name: tcp-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hotrod
  sessionAffinity: None
  type: LoadBalancer